[pytest]
log_cli = true
log_cli_level = INFO
log_cli_date_format = %Y-%m-%dT%H:%M:%SZ
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)

testpaths = test-suites
python_files = test_*.py
addopts = -ra --strict-markers
markers =
    krkn: Krkn chaos scenario.
    vm: RHOV VM tests.
    vm__br: RHOV VM tests using `benchmark-runner`.
