apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "${VM_NAME}"
  namespace: windows-bsod
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: "${VM_NAME}"
        kubevirt.io/domain: "${VM_NAME}"
    spec:
      nodeSelector:
        memory-backend: enabled
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
          model: EPYC-Genoa
          features:
            - name: skip-l1dfl-vmentry
              policy: require
            - name: mds-no
              policy: require
            - name: gds-no
              policy: require
            - name: pschange-mc-no
              policy: require
            - name: rdctl-no
              policy: require
            - name: erms
              policy: disable
            - name: fsrm
              policy: disable
            - name: ssbd
              policy: require
            - name: avx-vnni
              policy: require
            - name: tsc-scale
              policy: require
            - name: vmcb-clean
              policy: require
            - name: flushbyasid
              policy: require
            - name: pause-filter
              policy: require
            - name: pfthreshold
              policy: require
            - name: v-vmsave-vmload
              policy: require
            - name: vgif
              policy: require
        memory:
          guest: "16Gi"
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        features:
          smm: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              enabled: true
              spinlocks: 8191
            synic: {}
            synictimer:
              enabled: true
            frequencies: {}
            reenlightenment: {}
            ipi: {}
            runtime: {}
            reset: {}
        firmware:
          bootloader:
            efi:
              secureBoot: true
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: virtiocontainerdisk
              cdrom:
                bus: sata
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
          inputs:
            - type: tablet
              bus: usb
              name: tablet
        machine:
          type: q35
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
          limits:
            memory: "16Gi"
            cpu: "4"
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: "${VM_NAME}"
        - name: virtiocontainerdisk
          containerDisk:
            image: container-native-virtualization/virtio-win:v4.12-1784795134
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: win-admin-secret
